from pygame import USEREVENT

# Events
SONG_END_EVENT = USEREVENT + 1
ENEMY_DESTROYED_EVENT = USEREVENT + 2
BOSS_BATTLE_EVENT = USEREVENT + 3
DISPLAY_MESSAGE_EVENT = USEREVENT + 4
END_LEVEL_EVENT = USEREVENT + 5
END_GAME_EVENT = USEREVENT + 6

# Constants
SCREEN_SIZE = (800, 600)

# Colors
COLOR_BLACK = (0, 0, 0)
