from pygame import USEREVENT

# Events
SONG_END_EVENT = USEREVENT + 1
ENEMY_DESTROYED_EVENT = USEREVENT + 2
NEED_RELOAD_EVENT = USEREVENT + 3
RELOAD_EVENT = USEREVENT + 4
BOSS_BATTLE_EVENT = USEREVENT + 5

# Constants
SCREEN_SIZE = (800, 600)

# Colors
COLOR_BLACK = (0, 0, 0)
